/*
Role: Session API client service.
What it does: Wraps `/sessions` endpoints used for session setup, live interview completion, transcription, and reporting.
Where used: Called by dashboard/session views and interview room hooks.
Why it exists: Centralizes HTTP contracts so UI layers avoid direct axios calls.
*/

import axiosInstance from '../lib/axiosInstance';

export const sessionService = {
  /**
   * POST /sessions/:id/generate-questions
   * Generates questions if not already generated, marks session as in-progress,
   * and returns the questions array for the live room to use.
   */
  startAndFetchQuestions: async (sessionId, options = {}) => {
    const response = await axiosInstance.post(`/sessions/${sessionId}/generate-questions`, options);
    return response.data; // { success, questions: [{_id, questionText}] }
  },

  /**
   * POST /sessions
   * Creates a manual custom session
   */
  createCustomSession: async (data) => {
    const response = await axiosInstance.post('/sessions', data);
    return response.data;
  },

  /**
   * PUT /sessions/reorder
   * Updates the order of multiple sessions
   */
  reorderSessions: async (updates) => {
    const response = await axiosInstance.put('/sessions/reorder', { updates });
    return response.data;
  },

  /**
   * PATCH /sessions/:id/abandon
   * Marks the session as abandoned
   */
  abandonSession: async (sessionId) => {
    const response = await axiosInstance.patch(`/sessions/${sessionId}/abandon`);
    return response.data;
  },

  /**
   * POST /sessions/:id/complete
   * Saves all user answers and marks the session as completed
   */
  completeSession: async (sessionId, answers) => {
    const response = await axiosInstance.post(`/sessions/${sessionId}/complete`, { answers });
    return response.data;
  },

  /**
   * POST /sessions/transcribe
   * Transcribes an audio blob using Groq Whisper via the backend
   */
  transcribeAudio: async (audioBlob) => {
    const formData = new FormData();
    // Append the blob with a generic webm filename so multer processes it properly
    formData.append('audio', audioBlob, 'audio.webm');
    
    const response = await axiosInstance.post('/sessions/transcribe', formData, {
      headers: {
        'Content-Type': 'multipart/form-data',
      },
    });
    return response.data.text;
  },
  
  /** Get a detailed report for a session generated by AI */
  getSessionReport: async (sessionId) => {
    const response = await axiosInstance.get(`/sessions/${sessionId}/report`);
    return response.data;
  }
};

